### ISSUE TITLE
No rewards.npy file in hopper

### ISSUE THREAD

**Issue by debajoy** [gabrieletiboni/random-envs#1]
Hi sir,

how can we generate the rewards.npy file for the hopper_10000 file ?

**Comment by gabrieletiboni** [comment]
Dear @debajoy,

You should open a related issue in the dedicated [dropo repo](https://github.com/gabrieletiboni/dropo), as the random-envs repo is not involved and does not contain offline data.

Regarding your question, the offline data used by DROPO doesn't contain the reward information, as it's not needed. I'd say you have two options:
- (recommended) you just create a new offline dataset of N transitions yourself, by running a previously trained oracle policy on the target domain (or semi-converged, or even [random](https://gabrieletiboni.github.io/adr-benchmark/)).
- you can replay the offline trajectories by starting from the same state and executing the same actions. The nominal Hopper dynamics parameters have been used to collect the trajectories. 

A sample script for collecting offline data could look something like this:
```
states = []
next_states = []
actions = []

max_n_transitions = 500

env = gym.make('RandomHopper-v0')
state = env.reset()

for i in range(max_n_transitions):
        
    action = env.action_space.sample()

    states.append(state)
    actions.append(action)  # random action
    
    state, reward, done, info = env.step(action)
    next_states.append(state)

    if done:
        print('Exited early')
        break
```
